fixed folia scheduler noclassdeffounderror on plugin enable fixed dimension/world naming losing capitalization improved naming system to preserve case sensitivity fixed preset system loading/creation behavior fixed preset_not_found message not being used improved void preset handling general fixes and message improvements